version: '3.7'
services:
  app:
    image: spring-boot-app:latest
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresdb:5432/keycloak
      SPRING_DATASOURCE_USERNAME: keycloak
      SPRING_DATASOURCE_PASSWORD: keycloak
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
    networks:
      - app-network

  react:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:80
    depends_on:
      - app
    networks:
      - app-network

  postgresdb:
    image: postgres:13.2
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
