version: '3.7'
services:
  app:
    image: spring-boot-app:latest
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresdb:5432/keycloak
      SPRING_DATASOURCE_USERNAME: keycloak
      SPRING_DATASOURCE_PASSWORD: keycloak
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
    ports:
      - 8080:8080
    networks:
      - app-network
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres:13.2
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak
    ports:
      - 5432:5432
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REACT_APP_API_BASE_URL: http://127.0.0.1:8080
    ports:
      - 3000:3000
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
